### ISSUE TITLE
Issue with CustomRecord saved search

### ISSUE THREAD

**Issue by spurnaye** [NetSweet/netsuite#164]
Hello,
Here is the code I am using to pull a custom search.

results =  NetSuite::Records::CustomRecord.search({
  saved: <search_internal_id>,   # your saved search internalId
  basic: [{
    field: 'recType',
            operator: 'is',
            value: ::NetSuite::Records::CustomRecordRef.new(internal_id: <internal_id>)
    }]
}).results

I see the successful output from Netsuite as xml is correctly getting printed with success flag. But I see following error:
gems/ruby-2.1.3/gems/netsuite-0.3.3/lib/netsuite/support/search_result.rb:64:in `block in initialize': undefined method `search_joins=' for #<NetSuite::Records::CustomRecord:0x007fdddb1ab510> (NoMethodError)
	from .rvm/gems/ruby-2.1.3/gems/netsuite-0.3.3/lib/netsuite/support/search_result.rb:40:in `each'
	from .rvm/gems/ruby-2.1.3/gems/netsuite-0.3.3/lib/netsuite/support/search_result.rb:40:in `initialize'
	from .rvm/gems/ruby-2.1.3/gems/netsuite-0.3.3/lib/netsuite/actions/search.rb:241:in `new'
	from .rvm/gems/ruby-2.1.3/gems/netsuite-0.3.3/lib/netsuite/actions/search.rb:241:in `search'
	from test.rb:88:in `<main>'

**Comment by feigner** [comment]
I had a similar issue doing a search against InventoryItems. I monkeypatched the record class by adding `attr_accessor :search_joins` and things seem to be working for me.

**Comment by feigner** [comment]
Also, if you don't want to change that class, I believe that you can avoid a search join by specifying `returnSearchColumns: false` in your search preferences.

**Comment by iloveitaly** [comment]
This is fixed for CustomRecords with https://github.com/NetSweet/netsuite/commit/7801251c21379ddb9332f205f8aee7c30f3f1b5a

Feel free to submit a PR for the InventoryItem fix! Also, would be great to have a PR with some documentation on how `returnSearchColumns`works.
