### ISSUE TITLE
Validate users

### ISSUE THREAD

**Issue by rept** [NetSweet/netsuite#178]
Hi,

Thanks for this great library.  I'm wondering the following: I have set up one webservice user through which I would like to make all requests.  In the company there exist > 150 users.  I would like to be able to validate a user by making a call to the NetSuite webservice.

Suppose a new user logs in, in my application, then it should call the NetSuite backend (through my webservice login) and check if it's a valid user.  If it's the case the user can be created in my application automatically.  If it already exists then the user is logged in.

Does this functionality exist?  I found this link: http://blog.prolecto.com/2015/01/24/netsuite-easy-alternative-to-single-sign-on-authentication/ and the "Authentication Restlet API" seems to be what I need.  I'm wondering if something like this is possible in NetSweet/netsuite?

Thanks in advance for shedding some light on this.

**Comment by iloveitaly** [comment]
You could use the [login action](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/actions/login.rb) to test for a valid login, or use SSO (check out [using non-standard operations](https://github.com/NetSweet/netsuite#non-standard-operations) for more info.

I've written a devise adaptor to do NS user authentication and then create a resulting devise user if login is successful. Reach out to me via email if this would be helpful for your use case.

Hope this helps!
