### ISSUE TITLE
Join and getting values of other records in a search

### ISSUE THREAD

**Issue by rept** [NetSweet/netsuite#179]
Hi,

I'm checking out this pull request to be able to use ProjectTask: https://github.com/NetSweet/netsuite/pull/63  this works great (any idea when it will be merged?).

I'm doing this search:

    NetSuite::Records::ProjectTask.search( criteria: {basic: [{field: 'assignee',operator: 'anyOf',value: [NetSuite::Records::CustomRecordRef.new(:internal_id => 57957)]}]})

this works fine.  However it doesn't return the job name.  When I look in the documentation of NetSuite is see under "Search Joins" Job so it must be joinable but it's not clear to me how to join.  I tried adding 

    ,  jobJoin: [])

to it, but it doesn't return any extra columns.  In your examples of joining you set some conditions, is this obligated?  I only want to join to be able to get the parent fields in one go as well.

Another question: it it possible to limit the number of columns returned by a search?  Now for example I'm getting back the company ID, name etc while that's excess data...

Thanks in advance for any assistance.

**Comment by iloveitaly** [comment]
> any idea when it will be merged?

It needs to be rebased to master before merging :( If you could get it rebased I'd be happy to merge it in!

> to it, but it doesn't return any extra columns. In your examples of joining you set some conditions, is this obligated?

Take a look at the `body_fields_only` option in the documentation. I think that is what you are looking for.

> it it possible to limit the number of columns returned by a search?

You can, although it ain't pretty. check out the `columns` option in the readme.md
