### ISSUE TITLE
Multiuser support

### ISSUE THREAD

**Issue by adambedford** [NetSweet/netsuite#180]
What is the best way to go about using this library in a multiuser environment? I see that a `credentials` hash can be passed to `Netsuite::Connection`, but it doesn't seem like there is a way to initialize a `Netsuite::Connection` and then use it for all requests. Is there a good way to do this without having to pass the `credentials` hash each time?

**Comment by iloveitaly** [comment]
Most calls ([add, for example](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/actions/add.rb#L15-L17)) allow you to pass user credentials in. You have two main options:

1. Pass user credentials into the app
2. Set the global NS credentials to your user's credentials. This could be dangerous depending on your use case.

Hope this helps!
