### ISSUE TITLE
Follow 302 redirects to support different data centers & endpoints

### ISSUE THREAD

**Issue by adambedford** [NetSweet/netsuite#185]
Some NetSuite accounts are hosted at different data centers than others. Some accounts are hosted at `webservices.na1.netsuite.com` instead of `webservices.netsuite.com`. NetSuite issues a 302 redirect when you hit the wrong endpoint, but this library/Savon doesn't follow that redirect and instead throws an error.

Here's the result:

```
11:54:26 jobs.1 | HTTP error (302): <html><head><title>302 Moved Temporarily</title></head>
11:54:26 jobs.1 | <body bgcolor="#FFFFFF">
11:54:26 jobs.1 | <p>This document you requested has moved temporarily.</p>
11:54:26 jobs.1 | <p>It's now at <a href="https://webservices.na1.netsuite.com/dcrf.nl?k=8f4cc13b5aa7f060f29e88eb0cfa9dcdc51ec7cd1b3e638f1f229ba0d0f8df55&amp;dcrdt=&#37;2Fservices&#37;2FNetSuitePort_2015_1&amp;dcid=001&amp;dch=532d686d3db56ada8bb4f325c1630e077a5f3692d50f9787d02721adde22b7b1&amp;NS_VER=2015.1.0&amp;dcsid=LTn9VcXdJSrhjYfqwQnvTjLpTwkWSnJP5jnrkvKF1TC2zGgppT6cQvkTG5pfYhbGDLJXpl99wQT2LVnRlrsN1sLypZpTv0l03zQMtdzPYQyzhgGgsKRYFT95QvY0fJnL!185036389">https://webservices.na1.netsuite.com/dcrf.nl?k=8f4cc13b5aa7f060f29e88eb0cfa9dcdc51ec7cd1b3e638f1f229ba0d0f8df55&amp;dcrdt=&#37;2Fservices&#37;2FNetSuitePort_2015_1&amp;dcid=001&amp;dch=532d686d3db56ada8bb4f325c1630e077a5f3692d50f9787d02721adde22b7b1&amp;NS_VER=2015.1.0&amp;dcsid=LTn9VcXdJSrhjYfqwQnvTjLpTwkWSnJP5jnrkvKF1TC2zGgppT6cQvkTG5pfYhbGDLJXpl99wQT2LVnRlrsN1sLypZpTv0l03zQMtdzPYQyzhgGgsKRYFT95QvY0fJnL!185036389</a>.</p>
11:54:26 jobs.1 | </body></html>
11:54:26 jobs.1 | : /Users/Adam/.rvm/gems/ruby-2.1.2/gems/savon-2.3.3/lib/savon/response.rb:86:in `raise_soap_and_http_errors!'
11:54:26 jobs.1 | /Users/Adam/.rvm/gems/ruby-2.1.2/gems/savon-2.3.3/lib/savon/response.rb:14:in `initialize'
11:54:26 jobs.1 | /Users/Adam/.rvm/gems/ruby-2.1.2/gems/savon-2.3.3/lib/savon/operation.rb:64:in `new'
11:54:26 jobs.1 | /Users/Adam/.rvm/gems/ruby-2.1.2/gems/savon-2.3.3/lib/savon/operation.rb:64:in `create_response'
11:54:26 jobs.1 | /Users/Adam/.rvm/gems/ruby-2.1.2/gems/savon-2.3.3/lib/savon/operation.rb:55:in `call'
11:54:26 jobs.1 | /Users/Adam/.rvm/gems/ruby-2.1.2/gems/savon-2.3.3/lib/savon/client.rb:36:in `call'
11:54:26 jobs.1 | /Users/Adam/Mavenlink/netsuite/lib/netsuite/actions/search.rb:33:in `request'
11:54:26 jobs.1 | /Users/Adam/Mavenlink/netsuite/lib/netsuite/support/requests.rb:19:in `call'
11:54:26 jobs.1 | /Users/Adam/Mavenlink/netsuite/lib/netsuite/support/requests.rb:13:in `call'
11:54:26 jobs.1 | /Users/Adam/Mavenlink/netsuite/lib/netsuite/actions/search.rb:238:in `search'
```

Changing the WSDL to the correct endpoint works, but this isn't a long-term solution and doesn't allow for a multiuser situation where different accounts are on different servers.

Maybe this is a Savon issue?

**Comment by iloveitaly** [comment]
Right now this is supported manually:

```
NetSuite::configuration.wsdl = 'https://webservices.na1.netsuite.com/wsdl/v2014_1_0/netsuite.wsdl'
```

Digging through the return result and determining the correct datacenter would be add a good bit of complexity to the code.

Since this only needs to be done once per NS account, I think leaving this up to the user is the best approach. What do you think?

**Comment by adambedford** [comment]
My use case might be a little unique in that we're building an app that is multiuser (and multi NS account). I'm passing a credentials hash for the current user per request containing email, password, acct number - can the wsdl path be passed in here too? If so, that would definitely solve the issue.

**Comment by iloveitaly** [comment]
I've worked on a similar app before: you can't set the WSDL per-request at this point. Although, a quick modification to the `connection` method would allow you to customize the WSDL path per-credential.

I would recommend creating a `User.configure_netsuite` method to setup the current process/thread to use the correct NetSuite credentials. I would throw all NS requests into a queue; the queue job processor should be responsible for loading the correct user and configuring the correct credentials.

**Comment by drewish** [comment]
Personally I found the following bit of the README confusing:
```
  # optionally specify full wsdl URL (to switch to sandbox, for example)
  wsdl          "https://webservices.sandbox.netsuite.com/wsdl/v#{api_version}_0/netsuite.wsdl"

  # or specify the sandbox flag if you don't want to deal with specifying a full URL
  sandbox   true
```
I had no idea if I was on a sandbox site or not (turned out I wasn't) but took some manual trail and error to realize I needed to end up with:
```
wsdl "https://webservices.na1.netsuite.com/wsdl/v#{api_version}_0/netsuite.wsdl"
```

It's a bit orthogonal to this issue, but I'm commenting mostly because I saw the 302s when I was trying to find the right configuration settings.

**Comment by jayhahn** [comment]
@iloveitaly Does this application still not support setting WSDL per-request? We are also in a similar situation with multiuser/multi-NS accounts. Seems like NetSuite's official recommendation is that we always dynamically check the url per account
https://system.netsuite.com/app/help/helpcenter.nl?fid=section_N3494684.html

**Comment by iloveitaly** [comment]
@jayhahn not yet, feel free to submit a PR! Workaround now is to `NetSuite.configure` and then run a `NetSuite.configure { reset! }` after the call is complete.
