### ISSUE TITLE
SuiteTalk Having Trouble Connecting via SSL

### ISSUE THREAD

**Issue by iloveitaly** [NetSweet/netsuite#188]
I'm getting various SSL related errors in a couple different NetSuite SuiteTalk integrations for a couple clients.

Here is the error I'm seeing:

```
SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure`
```

And another less verbose error:

```
     Errno::ECONNRESET:
       Connection reset by peer - SSL_connect
```

Here are some possible related issues:

* http://stackoverflow.com/questions/27936062/connection-reset-by-peer-ssl-connect-when-opening-a-url
* http://railsapps.github.io/openssl-certificate-verify-failed.html
* https://mattbrictson.com/tls-error-with-ruby-client-and-tomcat-server

Chrome reports this SSL error:

![screen shot 2015-05-29 at 6 39 19 pm](https://cloud.githubusercontent.com/assets/150855/7894306/c4d9f62a-0635-11e5-9a5f-1bed79fcec22.png)

**Comment by iloveitaly** [comment]
Closing this out, ended up being a NetSuite server issue. The associated commit *did* fix the issue while it was occurring.

**Comment by jwebbstevens** [comment]
@iloveitaly do you know the root of the error?  Was it purely NetSuite Server and did it resolve on the NetSuite server side or because of the commit?

**Comment by iloveitaly** [comment]
The error was purely on the NetSuite server side. However, I believe this commit would have successfully worked around the NetSuite server error.
