### ISSUE TITLE
Searching for items based on Site Category

### ISSUE THREAD

**Issue by tamagokun** [NetSweet/netsuite#189]
This isn't entirely related to this library, but there aren't seemingly many places to turn when having trouble with NetSuite's APIs. Maybe someone has had a similar experience.

I am working on some nonInventorySaleItem searches, of which many are associated to particular Site Categories. I noticed in the Schema Browser page for ItemBasicSearch, there is a `category` field to specify a record ref for a category. Though, it doesn't seem to be working. It just appears to ignore the search field. There is no error returned.

Has anyone ever needed to do this?

Here is an example of my search:

```ruby
search = NetSuite::Records::NonInventorySaleItem.search({
  preferences: {
    body_fields_only: true,
    page_size: 10,
  },
  basic: [
    {
      field: 'category',
      operator: 'anyOf',
      type: 'SearchMultiSelectField',
      value: [
        NetSuite::Records::RecordRef.new(:internal_id => 49217795)
      ]
    },
    {
      field: 'isInactive',
      value: false
    }
  ]
})
```

**Comment by iloveitaly** [comment]
> It just appears to ignore the search field. There is no error returned.

Does it appear to be ignoring the field because the results contain items where `category != 49217795`?

Note that `NonInventorySaleItem.search` does not actually restrict the seach just just `NonInventorySaleItem`s, you have to define the item types you want to search over. Check out the `NetSuite::Records::InventoryItem.search` example in the readme for an example.

**Comment by tamagokun** [comment]
> Does it appear to be ignoring the field because the results contain items where category != 49217795?

No, it seems to exclude it entirely from the search. So, if I remove that field from the search and re-run it. I get the same exact set of items.

I've added:

```ruby
{
  field: 'type',
  operator: 'anyOf',
  type: 'SearchEnumMultiSelectField',
  value: ["_nonInventoryItem"]
},
```

but still no luck with category. It seems like perhaps the `category` field isn't referring to site categories, but something else.

**Comment by tamagokun** [comment]
Turns out this is a bug in their API. Someone at NetSuite is looking into it.
