### ISSUE TITLE
Anyone able to use Subsidiary Lists?

### ISSUE THREAD

**Issue by drewish** [NetSweet/netsuite#190]
I'm trying to specify a subsidiary list when creating a `ServiceSaleItem` using the syntax I found in [assembly_item_spec.rb](https://github.com/NetSweet/netsuite/blob/master/spec/netsuite/records/assembly_item_spec.rb#L26-L31):
```ruby
      subsidiary_list: {
        record_ref: [
          { internal_id: 1 },
        ]
      },
```

The XML it's generating for the upsert looks like:
```xml
<platformMsgs:upsert>
  <platformMsgs:record xsi:type="listAcct:ServiceSaleItem" platformMsgs:externalId="gold">
    <listAcct:subsidiaryList>
      <platformCore:recordRef>
        <platformMsgs:internalId>1</platformMsgs:internalId>
      </platformCore:recordRef>
    </listAcct:subsidiaryList>
    <listAcct:itemId>gold</listAcct:itemId>
    <listAcct:displayName>Gold plan</listAcct:displayName>
    <listAcct:salesDescription xsi:nil="true"/>
    <listAcct:taxSchedule internalId="1"/>
    <listAcct:isTaxable>true</listAcct:isTaxable>
  </platformMsgs:record>
</platformMsgs:upsert>
```
 
But I get the following error:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <soapenv:Fault>
      <faultcode>soapenv:Server.userException</faultcode>
      <faultstring>org.xml.sax.SAXException: Expected {urn:core_2013_2.platform.webservices.netsuite.com}internalId, found {urn:messages_2013_2.platform.webservices.netsuite.com}internalId</faultstring>
      <detail>
        <ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">partners-java10001.bos.netledger.com</ns1:hostname>
      </detail>
    </soapenv:Fault>
  </soapenv:Body>
</soapenv:Envelope>
```

Any clues what I'm doing wrong? I'd tried it with the 2011_2 and 2012_1 APIs as well with the same error.

When I fetch an existing `InventoryItem` with a subsidiary set the XML looks like:
```xml
<listAcct:subsidiaryList xmlns:platformCore="urn:core_2013_2.platform.webservices.netsuite.com">
  <platformCore:recordRef internalId="3">
    <platformCore:name>Honeycomb Holdings Inc.</platformCore:name>
  </platformCore:recordRef>
</listAcct:subsidiaryList>
```

**Comment by drewish** [comment]
Is there an easy way to bypass the objects and just generate XML manually?

**Comment by iloveitaly** [comment]
> Is there an easy way to bypass the objects and just generate XML manually?

You could you write your own custom object that could respond to `to_record` and output the ruby hash that savon expects and use that object for the `subsidiary_list `

---

The subsidiary list is not supported yet. It needs to use a custom list object similar [to the customer address books](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/records/customer.rb#L30). This is a bug, feel free to submit a PR!

**Comment by drewish** [comment]
@iloveitaly Once I dug in a little and found:
https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/records/inventory_item.rb#L61
https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/records/assembly_item.rb#L47

I was able to apply that to the `ServiceSaleItem` and now it's generating:
```xml
        <listAcct:subsidiaryList>
          <platformCore:recordRef internalId="1"/>
        </listAcct:subsidiaryList>
```
Which worked fine. So I opened #191.

**Comment by drewish** [comment]
Also ran into a problem with the invoice's subsidiary list which I've fixed on https://github.com/NetSweet/netsuite/pull/193

**Comment by drewish** [comment]
This is working great now.
