### ISSUE TITLE
Is there a `reload` or `refresh` method?

### ISSUE THREAD

**Issue by adambedford** [NetSweet/netsuite#197]
Is there a method to reload the record from the server? i.e. `some_job.reload` returns the most recent data from NetSuite.

**Comment by iloveitaly** [comment]
Right now there is nothing in place, but I really like this. Something like Stripe's `.refresh` would be great.

What I've been doing right now is `the_order = NetSuite::Records::SalesOrder.get(the_order.internal_id)`

Feel free to submit a PR for this :)

**Comment by iloveitaly** [comment]
Closing this out, let me know if you'd like any help with developing a PR for this!
