### ISSUE TITLE
How do I get purchase order data?

### ISSUE THREAD

**Issue by SEAnderson07** [NetSweet/netsuite#198]
I have been reviewing netsuite/lib/netsuite/records classes, and I do not see anything for purchase orders. I have tried finding a PO through calling the vendor record and the other related vendor records but have not had any success. Could you please point me in the right direction for retrieving purchase order data from NetSuite? Thanks!

**Comment by iloveitaly** [comment]
Here is the schema info for PurchaseOrder:

https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2014_1/schema/record/purchaseorder.html

This isn't supported by the gem yet. Feel free to create a PR for this feature!

**Comment by iloveitaly** [comment]
Closing this out, if you need help with a PR for this, let me know!
