### ISSUE TITLE
NoMethodError: undefined method `results' for false:FalseClass when using NetSuite::Records::InventoryItem.search.results_in_batches

### ISSUE THREAD

**Issue by glennfu** [NetSweet/netsuite#205]
Starting only July 24th, and every day since, this code has started failing, even though the server hasn't been updated. My code looks like this:

    search = NetSuite::Records::InventoryItem.search
    ns_items = []
    search.results_in_batches do |batch|
      puts "batch: #{batch.length}"
      ns_items += batch
    end
    ns_items.length

The output looks like this:

```
batch: 1000
D, [2015-07-28T13:18:49.907366 #42726] DEBUG -- : HTTPI GET request to webservices.na1.netsuite.com (net_http)
D, [2015-07-28T13:18:50.073021 #42726] DEBUG -- : HTTPI POST request to webservices.na1.netsuite.com (net_http)
batch: 1000
D, [2015-07-28T13:19:03.984211 #42726] DEBUG -- : HTTPI GET request to webservices.na1.netsuite.com (net_http)
D, [2015-07-28T13:19:04.164485 #42726] DEBUG -- : HTTPI POST request to webservices.na1.netsuite.com (net_http)
batch: 1000
D, [2015-07-28T13:19:19.110026 #42726] DEBUG -- : HTTPI GET request to webservices.na1.netsuite.com (net_http)
D, [2015-07-28T13:19:19.286344 #42726] DEBUG -- : HTTPI POST request to webservices.na1.netsuite.com (net_http)
NoMethodError: undefined method `results' for false:FalseClass
	from ~/.rvm/gems/ruby-2.2.2/bundler/gems/netsuite-8e2bdcdd9af1/lib/netsuite/support/search_result.rb:90:in `results_in_batches'
	from ~/.../app/models/inventory_item.rb:43:in `update_kit_ids'
```

I'm using netsuite gem 0.4.2 at revision: 8e2bdcdd9af1692ffab21945fafbb987be057375

Is there something I can do to fix this?

**Comment by iloveitaly** [comment]
What is the response XML from NetSuite? My hunch is your NS data center URL may have changed.

**Comment by glennfu** [comment]
I see about 60,000 lines of text per page, headed by stuff like this:

```
  <env:Body>
    <platformMsgs:searchMoreWithId>
      <platformMsgs:pageIndex>2</platformMsgs:pageIndex>
      <platformMsgs:searchId>WEBSERVICES_3790596_07282015704555776427959076_84c177e88e5da</platformMsgs:searchId>
    </platformMsgs:searchMoreWithId>
  </env:Body>
```

Beginning of the response looks like:
```
<platformCore:status isSuccess="true"/>
        <platformCore:totalRecords>3213</platformCore:totalRecords>
        <platformCore:pageSize>1000</platformCore:pageSize>
        <platformCore:totalPages>4</platformCore:totalPages>
        <platformCore:pageIndex>2</platformCore:pageIndex>
        <platformCore:searchId>WEBSERVICES_3790596_07282015704555776427959076_84c177e88e5da</platformCore:searchId>
        <platformCore:recordList>
        ...
```

The final request has:

```
  <env:Body>
    <platformMsgs:searchMoreWithId>
      <platformMsgs:pageIndex>4</platformMsgs:pageIndex>
      <platformMsgs:searchId>WEBSERVICES_3790596_07282015704555776427959076_84c177e88e5da</platformMsgs:searchId>
    </platformMsgs:searchMoreWithId>
  </env:Body>
```

and the response is:

```
I, [2015-07-28T13:52:21.715727 #42726]  INFO -- : SOAP response (status 200)
D, [2015-07-28T13:52:21.715951 #42726] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header>
    <platformMsgs:documentInfo xmlns:platformMsgs="urn:messages_2013_2.platform.webservices.netsuite.com">
      <platformMsgs:nsId>WEBSERVICES_3790596_072820157045055691055485131_84bbdd4489e6</platformMsgs:nsId>
    </platformMsgs:documentInfo>
  </soapenv:Header>
  <soapenv:Body>
    <searchMoreWithIdResponse xmlns="urn:messages_2013_2.platform.webservices.netsuite.com">
      <platformCore:searchResult xmlns:platformCore="urn:core_2013_2.platform.webservices.netsuite.com">
        <platformCore:status isSuccess="false">
          <platformCore:statusDetail type="ERROR">
            <platformCore:code>RCRD_DSNT_EXIST</platformCore:code>
            <platformCore:message>That record does not exist.</platformCore:message>
          </platformCore:statusDetail>
        </platformCore:status>
      </platformCore:searchResult>
    </searchMoreWithIdResponse>
  </soapenv:Body>
</soapenv:Envelope>
```

It's using the same search id of `WEBSERVICES_3790596_07282015704555776427959076_84c177e88e5da` in each of those requests, including the final one.

**Comment by iloveitaly** [comment]
Do you have multiple requests hitting the same NS user at the same time? Or do you queue everything in a single background worker?

If you execute another NS search it will invalidate the current NS search. This could be the source of the issue.

What does the initial search request XML look like?

**Comment by glennfu** [comment]
Normally it's a daily background task. Right now I'm testing by running it manually. Only this 1 search is happening. Here's the initial search request:

```
I, [2015-07-28T21:08:42.623374 #42726]  INFO -- : SOAP request: https://webservices.na1.netsuite.com/services/NetSuitePort_2013_2
I, [2015-07-28T21:08:42.624685 #42726]  INFO -- : SOAPAction: "search", Content-Type: text/xml;charset=UTF-8, Content-Length: 2047
D, [2015-07-28T21:08:42.626171 #42726] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:platformMsgs="urn:messages_2013_2.platform.webservices.netsuite.com" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:platformCore="urn:core_2013_2.platform.webservices.netsuite.com" xmlns:platformCommon="urn:common_2013_2.platform.webservices.netsuite.com" xmlns:listRel="urn:relationships_2013_2.lists.webservices.netsuite.com" xmlns:tranSales="urn:sales_2013_2.transactions.webservices.netsuite.com" xmlns:tranPurch="urn:purchases_2013_2.transactions.webservices.netsuite.com" xmlns:actSched="urn:scheduling_2013_2.activities.webservices.netsuite.com" xmlns:setupCustom="urn:customization_2013_2.setup.webservices.netsuite.com" xmlns:listAcct="urn:accounting_2013_2.lists.webservices.netsuite.com" xmlns:tranBank="urn:bank_2013_2.transactions.webservices.netsuite.com" xmlns:tranCust="urn:customers_2013_2.transactions.webservices.netsuite.com" xmlns:tranInvt="urn:inventory_2013_2.transactions.webservices.netsuite.com" xmlns:listSupport="urn:support_2013_2.lists.webservices.netsuite.com" xmlns:tranGeneral="urn:general_2013_2.transactions.webservices.netsuite.com" xmlns:listMkt="urn:marketing_2013_2.lists.webservices.netsuite.com" xmlns:listWebsite="urn:website_2013_2.lists.webservices.netsuite.com" xmlns:fileCabinet="urn:filecabinet_2013_2.documents.webservices.netsuite.com" xmlns:listEmp="urn:employees_2013_2.lists.webservices.netsuite.com">
  <env:Header>
    <platformMsgs:passport>
      <platformCore:email>EMAIL</platformCore:email>
      <platformCore:password>PASSWORD</platformCore:password>
      <platformCore:account>ACCOUNT</platformCore:account>
      <platformCore:role internalId="18"/>
    </platformMsgs:passport>
    <platformMsgs:SearchPreferences/>
  </env:Header>
  <env:Body>
    <platformMsgs:search>
      <platformMsgs:searchRecord xsi:type="listAcct:ItemSearch"/>
    </platformMsgs:search>
  </env:Body>
</env:Envelope>

I, [2015-07-28T21:08:58.685533 #42726]  INFO -- : SOAP response (status 200)
D, [2015-07-28T21:08:59.076999 #42726] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header>
    <platformMsgs:documentInfo xmlns:platformMsgs="urn:messages_2013_2.platform.webservices.netsuite.com">
      <platformMsgs:nsId>WEBSERVICES_3790596_07282015678319884975951974_53f4d2662ed4a</platformMsgs:nsId>
    </platformMsgs:documentInfo>
  </soapenv:Header>
  <soapenv:Body>
    <searchResponse xmlns="urn:messages_2013_2.platform.webservices.netsuite.com">
      <platformCore:searchResult xmlns:platformCore="urn:core_2013_2.platform.webservices.netsuite.com">
        <platformCore:status isSuccess="true"/>
        <platformCore:totalRecords>3213</platformCore:totalRecords>
        <platformCore:pageSize>1000</platformCore:pageSize>
        <platformCore:totalPages>4</platformCore:totalPages>
        <platformCore:pageIndex>1</platformCore:pageIndex>
        <platformCore:searchId>WEBSERVICES_3790596_07282015678319884975951974_53f4d2662ed4a</platformCore:searchId>
        <platformCore:recordList>
          <platformCore:record xmlns:listAcct="urn:accounting_2013_2.lists.webservices.netsuite.com" internalId="205" xsi:type="listAcct:InventoryItem">
            <listAcct:createdDate>2013-11-13T14:04:30.000-08:00</listAcct:createdDate>
            <listAcct:lastModifiedDate>2015-07-21T05:43:46.000-07:00</listAcct:lastModifiedDate>
            <listAcct:purchaseDescription>Gift Wrapping Kraft Envelope</listAcct:purchaseDescription>
            <listAcct:cogsAccount internalId="133">
...
```

Every time I do this, it fails on pageIndex of 4 like shown in my previous comment. I can run this 5 times in a row, and it will always get the first 3 pages, and it will always fail on the 4th page.

**Comment by glennfu** [comment]
Any more suggestions for this? I still have it set up on the daily cron job, and it fails the same way every time. Should I open a support request directly to NetSuite or am I still in the right place here?

**Comment by iloveitaly** [comment]
> Any more suggestions for this? I still have it set up on the daily cron job, and it fails the same way every time. Should I open a support request directly to NetSuite or am I still in the right place here?

This isn't an issue with the gem: it's an issue with your NetSuite instance. I would try contacting NS support. Also, feel free to reach out via email, I may be able to point you in the right direction with some more information about your NS instance.

**Comment by glennfu** [comment]
I've been going back and forth with NetSuite support for the last two weeks, and I feel like we're speaking different languages. The only thing I've understood is that they want me to replicate this from within the NetSuite GUI. Unfortunately, I have no idea how to do that. I've tried asking them for clarification on how to do that with no success. Do you think you could suggest to me how to perform the same type of search within NetSuite? Thanks!

**Comment by iloveitaly** [comment]
Looks like it's just an item search:

```
    <platformMsgs:search>
      <platformMsgs:searchRecord xsi:type="listAcct:ItemSearch"/>
    </platformMsgs:search>
```

Just performing a generic item search within NetSuite should be enough. However, NetSuite support is incredibly hard to work with.

I'd recommend working around the issue rather than relying on their support. Here's what might work:

1. Use an advanced item search and only return internalIds
2. `get_all` on the list of internalIds returned by the search and iterate over that list as your search results.

I would also try decreasing your `pageSize` and set `body_fields_only = true`.

**Comment by glennfu** [comment]
I tried this:

```
    search = NetSuite::Records::InventoryItem.search({
      preferences: {
        body_fields_only: true,
        page_size: 100
      }
    })
```

but still got "NoMethodError: undefined method `results' for false:FalseClass" at page 160.

You mentioned an " advanced item search and only return internalIds". I tried to figure out what that meant, and after consulting the README the best I could come up with was this:

```
    search = NetSuite::Records::InventoryItem.search({
      columns: {
        'listAcct:basic' => [
          'platformCommon:internalId/' => {},
        ]
      }
    })
```

Unfortunately that doesn't work. I just see "TypeError: no implicit conversion of Symbol into Integer". Can you explain to me how to do what you're suggesting?

**Comment by iloveitaly** [comment]
Checkout the `# advanced search from scratch` section in the readme. You'll need a `criteria` and `basic` key as shown in that example.

I would also look to see if there is an item on that specific page that is erroring out that is causing the issue. SuiteScripts embedded inside NetSuite can cause some crazy edge cases!

**Comment by rudyyazdi** [comment]
Hey @glennfu I am running into the same problem, have you had any luck working around it?

Cheers,

**Comment by glennfu** [comment]
@rudyyazdi Yes! I'll share here in a gist the code I'm using now. I may be sharing more than is necessary for this situation but it's been a long time since I wrote it.

https://gist.github.com/glennfu/56f0bab456d0bccafe0b6aab5cb7f8a5

Another thing you might try first, I had to put all these guys inline, no idea why, to get a search working:

`search = NetSuite::Records::InventoryItem.search; ns_items = []; search.results_in_batches { |batch| ns_items += batch }; ns_items.length`

Moving them to separate lines caused it to blow up.

I hope something here helps!

**Comment by rudyyazdi** [comment]
Thanks @glennfu :)

**Comment by iloveitaly** [comment]
@rudyyazdi @glennfu Could you submit a PR for this fix? I would love to get a fix for this merged into master!

**Comment by rudyyazdi** [comment]
@iloveitaly first of all thanks for this gem, it's very well structured and I love working with it 😄 

I have just started working with Netsuite API and SOAP in general!

So it might take a little time before I am confident enough to write something that follows your design.

But if @glennfu does not have the time to do it, I'll definitely put it in my priorities 😄 

Cheers,

cc: @dnch

**Comment by iloveitaly** [comment]
@rudyyazdi sounds like a plan! Let me know what I can do to help!

**Comment by glennfu** [comment]
So rerunning the original code that reproduced the error from the OP, I no longer get the same XML response from NetSuite. I really think it must have been a bug on their end, and the code I provide is just an alternate, and more specific, way of searching for the content I really needed at the time. So I think really all I've offered is a potential workaround if your NetSuite server is acting funky.

For my code that extends the NetSuite module, I'm not sure if any of it is pull-request worthy. It certainly doesn't address this Issue, but it does add some convenience methods that were nice for me in my work. I don't know if that makes it generally helpful for addition to this gem. If you want to take a glance at it and tell me otherwise, I'd be happy to submit some part of it that you want in the project!
