### ISSUE TITLE
Support for new token based authentication and applicationIds with 2015_02 schema

### ISSUE THREAD

**Issue by thomaswitt** [NetSweet/netsuite#214]
NetSuite requires Application IDs (https://system.na1.netsuite.com/app/help/helpcenter.nl?fid=section_4399767063.html) beginning with Schema Version 2015_02. Currently there's no support for that.

Additionally, Token Based Authentication will be supported in addition to the Login/Password Scheme (https://system.na1.netsuite.com/app/help/helpcenter.nl?fid=section_4395622897.html). It'd be great if that'd be supported to in order to enhance security.

**Comment by iloveitaly** [comment]
That would be great, I agree! Feel free to submit a PR!

**Comment by iloveitaly** [comment]
Added support for applicationId: https://github.com/netsweet/netsuite#2015_2-applicationid-support

As far as token auth goes, you should be able to support it using `soap_header`. Would be great to have a native API in configuration for it though. If you have any ideas around that, feel free to submit a PR!
