### ISSUE TITLE
ship_address_list not a recordref in NetSuite::Records::SalesOrder

### ISSUE THREAD

**Issue by timting** [NetSweet/netsuite#217]
I'm just wondering why ship_address_list is not in the recordref list for the SalesOrder record type. It's in the schema for 2015.1: https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2015_1/schema/record/salesorder.html Am I missing something? If it's just an oversight, I'm happy to supply a (very simple) PR.

**Comment by iloveitaly** [comment]
Hey @timting!

The new address model isn't yet supported by the gem. We are making some progress on it here: https://github.com/NetSweet/netsuite/pull/213/files

Feel free to contribute to that PR!

**Comment by timting** [comment]
Thank you for this gem - it's helped save us a lot of time!

I think we're talking about two different things. I looked at the PR you referred to, and it only adds billing_address and shipping_address fields to the model. What I'm looking for is actually ship_address_list, which is a recordref. We already have bill_address_list in the recordref list, so I'm trying to understand why adding ship_address_list requires adding an address model?

**Comment by iloveitaly** [comment]
Ah! You are right! `billAddressList` is simply a record ref.

I've added this with ebaef3f47a797b18972ae64f22f4d6e87f78c388. Could you try out `HEAD` and let me know if that works for you?

**Comment by timting** [comment]
Haha - checked your pull request, and you added bill_address_list again (it already exists in line 30 of that file). ship_address_list is what I'm looking for.

Thanks for your quick response!

**Comment by iloveitaly** [comment]
Whoops! Sorry about that. Fixed.

**Comment by timting** [comment]
Thanks so much! I can't really test it right now, since we don't have the needed data for this, but I don't think there'll be any issues.
