### ISSUE TITLE
Are Single Use PromotionCodes supported?

### ISSUE THREAD

**Issue by deereb** [NetSweet/netsuite#221]
When I try a 

```ruby
        search = NetSuite::Records::PromotionCode.search(
          criteria: {
            basic: [{ field: 'internalIdNumber', operator: 'notEmpty' }]
          },
          preferences: { body_fields_only: false }
        )
```

I receive objects for my Single Use codes, But they are missing the code attributes. If I perform a simple get  `NetSuite::Records::PromotionCode.get(ns_internal_id)` I get a record not found error.

Does this gem support getting single use codes?

**Comment by iloveitaly** [comment]
What is the URL you see when viewing a single use code? I don't have any experience with them, but I would imagine they are really `PromotionCode`s.

**Comment by deereb** [comment]
This is the Netsuite url, is that what you were looking for?
`/app/crm/sales/referralcode.nl?id=xxxx`

I am now able to get the promotion using `NetSuite::Records::PromotionCode.get(xxxx)`
and this is the response object:

```ruby
#<NetSuite::Records::PromotionCode:0x007fd527a529a0
 @attributes=
  {:implementation=>#<NetSuite::Records::RecordRef:0x007fd527a52540 @attributes={}, @external_id=nil, @internal_id="default", @type=nil>,
   :display_line_discounts=>true,
   :is_inactive=>false,
   :rate=>"20.00%",
   :discount_type=>false,
   :start_date=>Mon, 12 Oct 2015 21:00:00 -0700,
   :is_public=>true,
   :exclude_items=>false},
 @external_id=nil,
 @internal_id="xxxx">
```

This has almost all the information I would expect, but it does not have the list of coupon codes that are associated with this promotion. Something like `codes: ['test1', 'test2',...]`

**Comment by iloveitaly** [comment]
> This has almost all the information I would expect, but it does not have the list of coupon codes that are associated with this promotion. Something like codes: ['test1', 'test2',...]

What does the XML response look like? The record class could be missing a field definition. There are missing fields/lists in the gem implementation, unfortunately.

**Comment by deereb** [comment]
Here is the response. The netsuite online documentation shows the codes listed under the tabs section [here](https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2015_1/script/record/promotioncode.html) and there doesn seem to be a separate object for them [here](https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2015_1/script/record/couponcode.html)

Is there a way of making a custom search with the gem to join these models? 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header>
    <platformMsgs:documentInfo xmlns:platformMsgs="urn:messages_2012_1.platform.webservices.netsuite.com">
      <platformMsgs:nsId>WEBSERVICES_737998_1013201516668755171574663813_57dd3fbcfc20</platformMsgs:nsId>
    </platformMsgs:documentInfo>
  </soapenv:Header>
  <soapenv:Body>
    <getResponse xmlns="urn:messages_2012_1.platform.webservices.netsuite.com">
      <readResponse>
        <platformCore:status xmlns:platformCore="urn:core_2012_1.platform.webservices.netsuite.com" isSuccess="true"/>
        <record xmlns:listMkt="urn:marketing_2012_1.lists.webservices.netsuite.com" internalId="xxxx" xsi:type="listMkt:PromotionCode">
          <listMkt:implementation xmlns:platformCore="urn:core_2012_1.platform.webservices.netsuite.com" internalId="default"/>
          <listMkt:displayLineDiscounts>true</listMkt:displayLineDiscounts>
          <listMkt:isInactive>false</listMkt:isInactive>
          <listMkt:discount xmlns:platformCore="urn:core_2012_1.platform.webservices.netsuite.com" internalId="738">
            <platformCore:name>20% Discount</platformCore:name>
          </listMkt:discount>
          <listMkt:rate>20.00%</listMkt:rate>
          <listMkt:discountType>false</listMkt:discountType>
          <listMkt:applyDiscountTo>_allSales</listMkt:applyDiscountTo>
          <listMkt:startDate>2015-10-12T21:00:00.000-07:00</listMkt:startDate>
          <listMkt:isPublic>true</listMkt:isPublic>
          <listMkt:excludeItems>false</listMkt:excludeItems>
        </record>
      </readResponse>
    </getResponse>
  </soapenv:Body>
</soapenv:Envelope>
```

I really appreciate you spending time to give me some feeback :)

**Comment by iloveitaly** [comment]
Looks like SuiteTalk doesn't support pulling the code lists via the PromotionCode object. Checkout the `getSelectValue` call (documentation on the front page). That might enable you to grab the list.
