### ISSUE TITLE
Sales Order - Update Custom Fields?

### ISSUE THREAD

**Issue by jfagan** [NetSweet/netsuite#224]
https://github.com/NetSweet/netsuite/issues/36 does a good job explaining how to update NS fields, but does anyone know how to update custom fields? i.e. 

fields = {
      entity: set_up_customer,
      item_list: build_item_list,
      transaction_bill_address: build_bill_address,
      shipping_cost: order_payload[:totals][:shipping],
      transaction_ship_address: build_ship_address,
      custom_field_list: ?
    }

sales_order.update fields.merge(handle_extra_fields)

**Comment by iloveitaly** [comment]
@jfagan Here's how to update custom fields:

```
sales_order = NetSuite::Records::SalesOrder.new
sales_order.custom_field_list.custentity_the_field = { internal_id: 123 }

fields = {
entity: set_up_customer,
item_list: build_item_list,
transaction_bill_address: build_bill_address,
shipping_cost: order_payload[:totals][:shipping],
transaction_ship_address: build_ship_address,
custom_field_list: sales_order.custom_field_list
}

sales_order.update fields.merge(handle_extra_fields)
```

**Comment by jfagan** [comment]
@iloveitaly - Thank you for your help with this, I REALLY do appreciate it! :) :+1:

**Comment by iloveitaly** [comment]
No problem! Happy to help!
