### ISSUE TITLE
Namespace for JournalEntry is wrong

### ISSUE THREAD

**Issue by roeyby** [NetSweet/netsuite#227]
The namespace include for netsuite/records/journal_entry.rb should be Namespaces::TranGeneral instead of Namespaces::TranSales. This can be verified by reviewing the SuiteTalk documentation:

https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2015_1/schema/record/journalentry.html

**Comment by iloveitaly** [comment]
Thanks! Could you submit a PR for this change?

**Comment by roeyby** [comment]
Done
