### ISSUE TITLE
Is there a way to do OR queries?

### ISSUE THREAD

**Issue by wOvalle** [NetSweet/netsuite#239]
I want to be able to search for Customers by firstName OR companyName. Is that possible in one request?

**Comment by iloveitaly** [comment]
Yes, but not using SuiteTalk alone :(

You can create a `OR` search in the GUI. I believe you can override the search values specified in the saved search via SuiteTalk which should allow you to perform a dynamic `OR` search using SuiteTalk.

It might be easier to either:

* run two separate searches, save the IDs returned by the searches in a set, and do an intersection of the set and run a `get_all` on the resulting IDs (ugly, I know...)
* combine the first name and company field in a single custom field using SuiteScript / Workflow / formular field and search on that.

Feel free to contact me offline with any details that might be specific to your NS instance. Hope this helps!

**Comment by wOvalle** [comment]
Yes, I was afraid of that. Thanks @iloveitaly for the workarounds!
