### ISSUE TITLE
How to query a transaction saved search

### ISSUE THREAD

**Issue by jeffyu** [NetSweet/netsuite#246]
This probably is not an issue or enhancement, but don't have anywhere to post for now.

Basically I have a transaction saved search, but I couldn't use the Invoice.search() with the saveId, it would return me a FalseClass. One more question, my saved search result got a formula(percentage), is that supported yet?

**Comment by iloveitaly** [comment]
@jeffyu Could you post your request and response XML?

The best place for these questions is the slack group. Do you mind joining the group and posting there? http://opensuite-slackin.herokuapp.com
