### ISSUE TITLE
Phone Field Search?

### ISSUE THREAD

**Issue by wOvalle** [NetSweet/netsuite#247]
Hello guys!

This question is not related directly with Api wrapper but the Api itself. Does anyone know if is possible to use other phone fields rather than officePhone in customer searches? If I search by homePhone or mobilePhone API throws the following error:

```
       <soapenv:Fault>
            <faultcode>soapenv:Server.userException</faultcode>
            <faultstring>com.netledger.util.schemabean.NLSchemaBeanException: homePhone not found on {urn:common_2015_2.platform.webservices.netsuite.com}CustomerSearchBasic</faultstring>
            <detail>
                <ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">partners-java10012.bos.netledger.com</ns1:hostname>
            </detail>
        </soapenv:Fault>
```

Keep up the good work!

**Comment by iloveitaly** [comment]
Unfortunately, it's doesn't look like it :(

https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2015_2/schema/search/customersearchbasic.html?mode=package

The best place for these questions is the slack group. Do you mind joining the group and posting there? http://opensuite-slackin.herokuapp.com
