### ISSUE TITLE
tax_1_amt will be translated to tax_1Amt instead of tax1Amt

### ISSUE THREAD

**Issue by obarth** [NetSweet/netsuite#303]
At vendor_bill_expense there is a field tax_1_amt. But the field cant not be set.
The web service claims: tax_1Amt not found.

Please merge. Thanks a lot.

https://github.com/NetSweet/netsuite/pull/302

**Comment by iloveitaly** [comment]
@obarth thanks for this! I'll need to run this through a set of integration tests I have built for some larger NS integrations to ensure it's backward compatible. I can't recall too many fields with a number in the field name, but I want to make sure there aren't any unintended side effects.

**Comment by obarth** [comment]
any news here?
I just noticed that it is still not in the head version. But it really fixes our problem.

:-)

**Comment by iloveitaly** [comment]
@obarth sorry for the delay here. Thanks for the bump!

Here are all of the fields in the NS gem that contain numbers.

```
>> puts NetSuite::Records.constants.map { |c| NetSuite::Records.const_get(c) }.select { |c| c.respond_to?(:fields) }.map(&:fields).map(&:to_a).flatten.uniq.select { |s| s =~ /[0-9]/ }.join("\n")
manufacturer_addr1
category1099misc
addr1
addr2
addr3
bill_addr1
bill_addr2
bill_addr3
exp_cost_disc_tax1_amt
exp_cost_tax_rate1
exp_cost_tax_rate2
handling_tax1_rate
handling_tax2_rate
item_cost_disc_tax1_amt
item_cost_tax_rate1
item_cost_tax_rate2
shipping_tax1_rate
shipping_tax2_rate
tax2_total
time_disc_tax1_amt
time_tax_rate1
time_tax_rate2
ship_addr1
ship_addr2
ship_addr3
tax1_amt
tax_rate1
tax_rate2
handling_tax2_amt
shipping_tax2_amt
password2
exp_cost_disc_tax_1_amt
exp_cost_tax_rate_1
exp_cost_tax_rate_2
handling_tax_1_rate
handling_tax_2_rate
item_cost_disc_tax_1_amt
item_cost_tax_rate_1
item_cost_tax_rate_2
shipping_tax_1_rate
shipping_tax_2_rate
tax_2_total
time_disc_tax_1_amt
time_tax_rate_1
time_tax_rate_2
tax1_acct
manufactureraddr1
return_address1
return_address2
ship_address1
ship_address2
state1_tax_number
unitprice1
unitprice2
taxitem1
taxitem2
is1099_eligible
tax_1_amt
tax_rate_1
tax_rate_2
```

I spot checked a bunch of them: your fix seems to work just great! Merging it in now. Closing this issue out.
