### ISSUE TITLE
saved search

### ISSUE THREAD

**Issue by vtharmalingam** [NetSweet/netsuite#311]
Hi,

I think  this is a great work done on this gem, but I am sorry to be very honest with you that the documentation is hopeless and for the users like me we end up wasting more time to figure out how it works. For instance, I tried to do a simple and common use case of searching by saved id. I searched and searched and wasted a few days and even thought of dumping this. But as a last resort, decided to write so that if at all a bug, will help you. I am sorry no offence meant by saying above - I wanted to share my honest feedback so that the great community work like this should be more user-friendly to take all people on-boarded. The doc somewhere saying go to "slack" for answers. I never known what slack what and how to do that, and there is no helpful guide to educate people either. It was even more frustrating as I wasted several unfruitful attempts to figure out there too. 

Anyways, here is the error I get when I do "saved search id".  
It gets me some records, then I get the error.

C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/netsuite-0.7.6/lib/netsuite/support/search_result.rb:50:in `block (2 levels) in initialize': undefined method `each_pair' for #<Array:0x0000000e434280> (NoMethodError)
Did you mean?  each_entry
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/netsuite-0.7.6/lib/netsuite/support/search_result.rb:46:in `each_pair'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/netsuite-0.7.6/lib/netsuite/support/search_result.rb:46:in `block in initialize'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/netsuite-0.7.6/lib/netsuite/support/search_result.rb:42:in `each'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/netsuite-0.7.6/lib/netsuite/support/search_result.rb:42:in `initialize'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/netsuite-0.7.6/lib/netsuite/actions/search.rb:254:in `new'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/netsuite-0.7.6/lib/netsuite/actions/search.rb:254:in `search'
	from C:/xxxx/NetSweetTest/NSInterface/saved_search.rb:67:in `salesorder_search'
	from C:/xxxx/NetSweetTest/NSInterface/saved_search.rb:99:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

This is how I invoked the search:
    
=====================================================
    # I defined a hash and passing that
    search = NetSuite::Records::SalesOrder.search(criteriaHash)
  
    # batch search
    search.results_in_batches do |batch|
      batch.each do |so|
        store_data(so, @@datamart)
      end
    end
=====================================================

I am not sure if i am so dump that I cannot make this work - I agree I am not great in Ruby, but I have 25 years of coding expertise with other languages. I thought of leveraging ruby as I heard lot of good feedback about this gem. 

Please educate me why am i getting this error.
And as I said, please do guide people to get on to the discussion forum smoothly.

Thanks,
Tharma

**Comment by iloveitaly** [comment]
> but I am sorry to be very honest with you that the documentation is hopeless and for the users like me we end up wasting more time to figure out how it works

I completely understand! The documentation is poor. Pull requests to improve the documentation is encouraged!

Can you join the open chat room and ask about this issue?

http://opensuite-slackin.herokuapp.com

I try not to use GH issues for general questions. Thanks!
