### ISSUE TITLE
Help adding netsuite mapSSO module?

### ISSUE THREAD

**Issue by david-forever** [NetSweet/netsuite#32]
I wanted to add a module for the mapSSO interface following this guide:

https://github.com/RevolutionPrep/netsuite/wiki/Contributing-to-the-Supported-NetSuite-API

However, I don't know how to determine where the function should live, i.e. in what module hierarchy?

I'll do a pull request if someone could help me get started.

Thanks,
David

**Comment by iloveitaly** [comment]
@bobbytables Awesome!! Open up a PR, I'm happy to collaborate.
