### ISSUE TITLE
Inventory Item Updates are not updating Netsuite

### ISSUE THREAD

**Issue by arosenk35** [NetSweet/netsuite#327]
I can create a new inventory item, get the item. when updating the item after getting it the data does not change within NetSuite. any ideas?

**Comment by arosenk35** [comment]
when trying and upsert, i get a soap error? 

    <soapenv:Fault>
      <faultcode>soapenv:Server.userException</faultcode>
      <faultstring>org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 2635; Element or attribute do not match QName production: QName::=(NCName':')?NCName. </faultstring>
      <detail>
        <ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">sb-partners-java051.svale.netledger.com</ns1:hostname>
      </detail>
    </soapenv:Fault>
  </soapenv:Body>
</soapenv:Envelope>

*** Savon::SOAPFault Exception: (soapenv:Server.userException) org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 2635; Element or attribute do not match QName production: QName::=(NC
Name':')?NCName.

**Comment by iloveitaly** [comment]
@arosenk35 The best place for these sort of questions (general usage) is the Slack group. Check it out and repost your question there:

http://opensuite-slackin.herokuapp.com/
