### ISSUE TITLE
Operator not found on SearchBooleanField

### ISSUE THREAD

**Issue by toobulkeh** [NetSweet/netsuite#33]
I'm new to the SuiteTalk API, but from what I can tell, this query SHOULD work:

```ruby
memorized_invoices = NetSuite::Records::Transaction.search({ criteria: { basic: [{ field: 'type', operator: 'anyOf', type: 'SearchEnumMultiSelectField', value: ["_invoice"]}, {field: 'memorized', value: true}]}})
```

But all I receive is a missing operator on SearchBooleanField:
```console
D, [2013-10-15T16:23:10.607161 #5131] DEBUG -- : HTTPI POST request to webservices.netsuite.com (curb)
Savon::SOAPFault: (soapenv:Server.userException) org.xml.sax.SAXException: operator not found on {urn:core_2011_2.platform.webservices.netsuite.com}SearchBooleanField
```

Any suggestions as to why it's missing an operator on the SearchBooleanField? From your example on [the main markdown page](https://github.com/RevolutionPrep/netsuite) (search for: ```# no operator for booleans```), a boolean field shouldn't need an operator.

I've done a basic google search, and haven't found much, except [a few PHP examples](http://www.webtrafficexchange.com/netsuite-php-search-tutorials) that show that they use the operator 'is', which doesn't work either.

Any ideas?

**Comment by iloveitaly** [comment]
Closing this out. Feel free to open this back up if you have any more information on this!
