### ISSUE TITLE
Fields that can _never_ be updated, should be excluded when performing an upsert

### ISSUE THREAD

**Issue by Senjai** [NetSweet/netsuite#345]
## Problem
Fields like `cost_estimate` cannot be updated on sales order items in NetSuite, and to my knowledge there is no way to allow them to be updated unless you use suitescript or the like. If we perform an upsert, we should probably avoid trying to update those values. 

## Expected Solution

`NetSuite::Records::SalesOrder.get(1234).upsert` should work in all cases. 

I might be missing really obvious reasons why this can't be the case. Please don't hesitate to let me know if I am.

**Comment by iloveitaly** [comment]
@Senjai The easiest way to handle this is to add this soap_header:

https://github.com/NetSweet/netsuite/commit/875c03b7e1aadc0d5b36b3c624cbc86fba3b4c11

Alternatively a list of read_only fields can be added to each record. This is more time consuming from a dev perspective, but feel free to submit a PR for any records that are causing you issues:

https://github.com/NetSweet/netsuite/blob/875c03b7e1aadc0d5b36b3c624cbc86fba3b4c11/lib/netsuite/records/invoice.rb#L42
