### ISSUE TITLE
update all fields or just the one pass in

### ISSUE THREAD

**Issue by diwu86** [NetSweet/netsuite#361]
Hi, we are using api_version 2017_1. According to your document, when we do an update a custom field list on a record,  ```
 you need to push ALL the values of ALL of the custom fields that you want set on the record
 you can't just push the values of the fields that you want to update: all of the values of
 other fields will then fall back to their default values```. However when we do something like this 
`customer.update custom_field_list: {
          custom_field: [
            { script_id: 'custitem_1', value: true, type: 'platformCore:BooleanCustomFieldRef' },
            { script_id: 'custitem_2', value: false, type: 'platformCore:BooleanCustomFieldRef' }
          ]
        }`
We don't see other fields get update to default value. So my question is whether the update is still update all fields and for the one we don't pass in, they will get set to default values?
Thanks

**Comment by iloveitaly** [comment]
Hello! For general usage questions, hop on the Slack group (check out the readme) and ask the community. GitHub issues is only used for gem code changes/improvements. Thanks!
