### ISSUE TITLE
Ambiguous authentication?

### ISSUE THREAD

**Issue by NoPretzel** [NetSweet/netsuite#368]
Using a direct connection with user/pass seems to work fine but when I use token based auth I always get this error.

Request the wrapper:

`<env:Header>
    <platformMsgs:tokenPassport>
      <platformCore:account>***FILTERED***</platformCore:account>
      <platformCore:consumerKey>***FILTERED***</platformCore:consumerKey>
      <platformCore:token>***FILTERED***</platformCore:token>
      <platformCore:nonce>***FILTERED***</platformCore:nonce>
      <platformCore:timestamp>***FILTERED***</platformCore:timestamp>
      <platformCore:signature algorithm="HMAC-SHA256">***FILTERED***
</platformCore:signature>
    </platformMsgs:tokenPassport>
    <platformMsgs:ApplicationInfo>
      <platformMsgs:applicationId>***FILTERED***</platformMsgs:applicationId>
    </platformMsgs:ApplicationInfo>
  </env:Header>
  <env:Body>
    <platformMsgs:get>
      <platformMsgs:baseRef xsi:type="platformCore:RecordRef" internalId="1397" type="customer"/>
    </platformMsgs:get>
  </env:Body>`

Response from Netsuite:

`  <soapenv:Body>
    <soapenv:Fault>
      <faultcode>soapenv:Server.userException</faultcode>
      <faultstring>Ambiguous authentication</faultstring>
      <detail>
        <platformFaults:invalidCredentialsFault xmlns:platformFaults="urn:faults_2016_1.platform.webservices.netsuite.com">
          <platformFaults:code>USER_ERROR</platformFaults:code>
          <platformFaults:message>Ambiguous authentication</platformFaults:message>
        </platformFaults:invalidCredentialsFault>
        <ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">partners-java10011.bos.netledger.com</ns1:hostname>
      </detail>
    </soapenv:Fault>
  </soapenv:Body>`

**Comment by iloveitaly** [comment]
@NoPretzel My hunch is you have token based auth setup incorrectly. GH issues are for coding-level issues only, hop on the slack group and ask this usage question there! Thanks.
