### ISSUE TITLE
Allow developers to add new Classifications

### ISSUE THREAD

**Issue by manmartinez** [NetSweet/netsuite#409]
Looks like the gem currently doesn't support the `add` operation on the `NetSuite::Records::Classification` objects, but this operation is supported by SuiteTalk.

My app needs to add new classifications programmatically, I've managed to work-around this by monkey-patching the `Classification` class:

```ruby
NetSuite::Records::Classification.class_eval do
  action :add
end
```

But it'd be great if we could add this to the main codebase, would you guys be interested in a PR?

**Comment by iloveitaly** [comment]
@manmartinez great idea! Adding this in now.
