### ISSUE TITLE
Having `Unexpected ERROR` when I try to list Projects , randomly from some `NetSuite_Ids`

### ISSUE THREAD

**Issue by march23** [NetSweet/netsuite#410]
Hi Folks

Since last Friday some user NetSuite Accounts are getting an unexpected error when we try to run this query:

`NetSuite::Records::Job.search(projectTaskJoin: [{
       field: 'assignee',
       operator: 'anyOf',
       type: 'ProjectTaskSearchBasic',
       value: [NetSuite::Records::RecordRef.new(:internal_id => context.employee_id)]
      }])`

We're getting the following issue:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header>
    <platformMsgs:documentInfo xmlns:platformMsgs="urn:messages_2015_2.platform.webservices.netsuite.com">
      <platformMsgs:nsId>WEBSERVICES_3403909_082720182078451197894647607_3b76ac3142f4</platformMsgs:nsId>
    </platformMsgs:documentInfo>
  </soapenv:Header>
  <soapenv:Body>
    <searchResponse xmlns="urn:messages_2015_2.platform.webservices.netsuite.com">
      <platformCore:searchResult xmlns:platformCore="urn:core_2015_2.platform.webservices.netsuite.com">
        <platformCore:status isSuccess="false">
          <platformCore:statusDetail type="ERROR">
            <platformCore:code>UNEXPECTED_ERROR</platformCore:code>
            <platformCore:message>An unexpected error occurred. Error ID: jlceo0s964c99cjvg9c3</platformCore:message>
          </platformCore:statusDetail>
        </platformCore:status>
      </platformCore:searchResult>
    </searchResponse>
  </soapenv:Body>
</soapenv:Envelope>`

Any ideas? this is the first time we 're having this issue, and it is ony happening with some selected employee ids.

Thanks

**Comment by iloveitaly** [comment]
@march23 unfortunately, this has been common with the 2018.1. It's an internal NS error and isn't triggered by a bug in the NS Gem. Most of the time it's just an intermittent failure that you can safely retry.

Join the slack group to ask the community for more advice: http://opensuite-slackin.herokuapp.com

**Comment by march23** [comment]
@iloveitaly thanks for your advice , I'll be reaching the NetSuite Slack community soon
