### ISSUE TITLE
Sandbox url not working with TBA version 2016-2

### ISSUE THREAD

**Issue by march23** [NetSweet/netsuite#413]
Hi Folks

I just got our new sandbox credentials with new TBA tokens in order to use it with your gem on our staging env, but I am unable to login using the sandbox option,  do we need to do something else to make it work?

**Comment by iloveitaly** [comment]
@march23 this is the sort of question that is best answered in the slack group. Join and repost your question there!

http://opensuite-slackin.herokuapp.com
