### ISSUE TITLE
Vendor Credit External ID field is missing

### ISSUE THREAD

**Issue by LNRexpress** [NetSweet/netsuite#418]
According to the NetSuite documentation for Vendor Credits [available here](http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2016_2/script/record/vendorcredit.html), vendor credits should have an external ID field; however, this field does not appear to be available in `NetSuite::Records::VendorCredit`.  Can this field be added?

**Comment by tatecarr** [comment]
@LNRexpress certainly, and lots of people that use the gem have submitted PRs to add fields/functionality over the years, so feel free to do the same.  Pretty minimal update - check out another record that already has it like [Sales Order](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/records/sales_order.rb) to see what that looks like.

**Comment by iloveitaly** [comment]
Thanks @tatecarr for answering this one! @LNRexpress I'll look out for a PR from you.

**Comment by LNRexpress** [comment]
PR created:  https://github.com/NetSweet/netsuite/pull/419
