### ISSUE TITLE
CustomRecordRef is initialized with an Array

### ISSUE THREAD

**Issue by LNRexpress** [NetSweet/netsuite#424]
When search results contain custom fields with type `xsi:type="platformCore:MultiSelectCustomFieldRef"`, the custom fields are parsed into a `Hash`.  [This block of code](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/records/custom_field_list.rb#L116-L118) is executed on the `Hash` to generate `CustomRecordRef` objects.  Executing `map` on a `Hash` results in the `entry` variable being of type `Array`.  This results in [this block of code](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/records/custom_record_ref.rb#L24-L28) being called, which does not work on `Arrays`.  As a result, the custom field value is not accessible in the search results.  Please see [this pull request](https://github.com/NetSweet/netsuite/pull/421) for a possible solution.

**Comment by iloveitaly** [comment]
This is fixed here https://github.com/NetSweet/netsuite/commit/3377c971d0cb727d81f4b4bc6e30edfbdfaccfd1
