### ISSUE TITLE
Regardless of Config, All Calls Go to Wrong DataCenter

### ISSUE THREAD

**Issue by imageaid** [NetSweet/netsuite#434]
I am attempting to update our NetSuite gem's configuration so that our requests go to the "right" data center. 

However, regardless of what I enter into the initializer, all requests go to the wrong data center, using the 'generic' wsdl: `https://webservices.netsuite.com/services/NetSuitePort_2017_2` as it appears to drop the `na2.` from the 'correct' URL (see below). 

In my configuration/initializer, I have specified one of two options: 

```
# config/initializers/netsuite.rb
NETSUITE_CONFIG = YAML.load_file(File.join(Rails.root, 'config', 'netsuite.yml'))[Rails.env].symbolize_keys

NetSuite.configure do
  reset!

  api_version   '2017_2'

  wsdl          "https://webservices.na2.netsuite.com/services/NetSuitePort_#{api_version}"
  # I have tried, with the same results, using one of the options below instead
  # wsdl          "https://OURACCT#.suitetalk.api.netsuite.com/wsdl/v#{api_version}_0/netsuite.wsdl"
  # wsdl_domain   'OURACCT#.suitetalk.api.netsuite.com'

  sandbox false
  account           NETSUITE_CONFIG[:api_account]
  consumer_key      NETSUITE_CONFIG[:consumer_key]
  consumer_secret   NETSUITE_CONFIG[:consumer_secret]
  token_id          NETSUITE_CONFIG[:token_id]
  token_secret      NETSUITE_CONFIG[:token_secret]

  read_timeout 100_000
  # let's save this stuff to its own log
  log File.join(Rails.root, 'log/netsuite.log')

  soap_header 'platformMsgs:ApplicationInfo' => {
    'platformMsgs:ignoreReadOnlyFields' => true
  }
end
```

The long and short is that no matter what I have in the initializer/config file, the library *only* makes requests to "https://webservices.netsuite.com/services/NetSuitePort_2017_2". I have even tried as `wsdl "http://dumburls.com/i/hate/netsuite"` as a WSDL URL and it still just goes to the URL noted above. 

One final note: if I change the API Version in the config file, it DOES change the request to `https://webservices.netsuite.com/services/NetSuitePort_2015_1` but still ignores whatever I have for `wsdl` or `wsdl_domain`. 

Any direction or suggestions would be most appreciated and thank you!

**Comment by tatecarr** [comment]
@imageaid Good place for questions like this is the slack channel, Mike tries to keep issues to just issues and not questions unless that leads to a bug/issue, and then an issue can be created of course. Join the slack channel by going here: http://opensuite-slackin.herokuapp.com/

But, to possibly answer your question, there is something funky with the `sandbox` config where it resets other config -- I forget exactly which, but I think the endpoint may be one of them. If you move the `sandbox false` to the top just above the `api_version` and use `wsdl_domain` not just `wsdl`, I think that may do the trick for you (and definitely use the account based URL for that).

**Comment by imageaid** [comment]
Ah crap! I totally spaced on adding a comment yesterday. I think you’re spot on with the sandbox resetting other configs. When I moved the `wsdl_domain` method below the other calls, making it the last one in the block, it help perfectly and all requests went to the right URL.

I forked the repo so I could explore the internals as I worked through this. Going to see if I can uncover where that’s happening and, if I can, I’ll submit a PR for review, etc.

Thanks for getting back to me and all the work on this gem. It really makes the hell that is working with NetSutie a little better :). Appreciate it (and the heads up on the slack channel, too!!).

**Comment by tatecarr** [comment]
Yep, it's easy to locate the problem sandbox bit. I think I was going to possibly submit a PR as well, but I think it might be a good idea to just nix the sandbox altogether -- the logic included with that flag is older and tied to the sandbox domain. So that was before NS got rid of the sandbox domain. Which was before they've now gone to account specific URLs for both prod 12345.app/suitetalk/etc... and for sandbox too 12345-sb1.app/suitetalk/etc.

So should probably look at removing sandbox, and making the `wsdl_domain` required -- then folks are setting it explicitly rather than any gem defaults, and it can be explicitly to a SB, or to a prod account. Thoughts @iloveitaly ?

**Comment by imageaid** [comment]
I do like the idea of making wsdl_domain required given NetSuite's removal of their internal router and new requirement for accounts to use those specific, account-based Data Center URLs.

**Comment by shaicoleman** [comment]
Related to #430

**Comment by iloveitaly** [comment]
https://github.com/NetSweet/netsuite/pull/473 Fixed this issue. Closing this out.
