### ISSUE TITLE
Unable to mark journal entry as approved

### ISSUE THREAD

**Issue by jerryjohnjacob** [NetSweet/netsuite#440]
When building journal entries, I set `approved` to `true`, but after sending to NetSuite, the line list still shows the status as 'Pending Approval'. Is [the field](https://github.com/NetSweet/netsuite/blob/6659d546d15837953aa7e6d750e7fd2dfa7418ea/lib/netsuite/records/journal_entry.rb#L12) not meant for that? Or do I need to set additional attributes to get this to work?

**Comment by iloveitaly** [comment]
Closing this out, ask these sort of usage questions on the slack group from here on out.
