### ISSUE TITLE
Saved search causes NoMethodError for record lacking :basic key

### ISSUE THREAD

**Issue by srchulo** [NetSweet/netsuite#442]
When I run a saved search like this:

```
search = NetSuite::Records::InventoryItem.search({
  saved: 123,
  preferences: {
    page_size: 1000,
  }
})
```

I get this error:

```
netsuite-0.8.5/lib/netsuite/support/search_result.rb:89:in block in initialize': undefined method []' for nil:NilClass (NoMethodError)
```

It looks like it's because of this line in search_result.rb:

```
if record[:basic][:internal_id]
```

Because there is no basic key in what is returned:

```
{:"@xmlns:list_acct"=>"urn:accounting_2018_2.lists.webservices.netsuite.com", :"@xsi:type"=>"listAcct:ItemSearchRow"}
```

I do get many valid return records, but the last one seems to have not `basic` key. I don't know if this is an actual record that is returned that is causing this, or a bug in the library.

I was able to fix this locally by adding:

```
record_list.each do |record|
  next unless record.key?(:basic) # fix?
```

But I don't know if that is really the correct way to handle this.

**Comment by iloveitaly** [comment]
@srchulo could you post the full XML request and response? That would be helpful!

**Comment by srchulo** [comment]
Huh, now I actually can't reproduce this. Maybe it was somehow intermittent? I'm going to take out the line that I added, and I will reopen this if I can reproduce it again.

**Comment by iloveitaly** [comment]
@srchulo strange! I wouldn't be surprised if it was an intermittent NS error. If you run into this again, let me know!
