### ISSUE TITLE
0.8.4 and 0.8.5 don't appear in the github releases

### ISSUE THREAD

**Issue by mawaldne** [NetSweet/netsuite#446]
Hello, 

I noticed on ruby gems theres a 0.8.4/0.8.5 release, but in github those releases don't appear:

Github:
https://github.com/NetSweet/netsuite/releases

Rubygems:
https://rubygems.org/gems/netsuite

Just curious whats up there. Thanks again for making this gem!

**Comment by iloveitaly** [comment]
@mawaldne I just forgot to tag them in GH. If you can post the SHAs here based on the git commit history I'd be happy to create the releases in GH.

**Comment by mawaldne** [comment]
@iloveitaly Found it:

For 0.8.4 its d8e83cf24dc254b0c6b531ad2d6ef1fd37d85f2a
```
commit d8e83cf24dc254b0c6b531ad2d6ef1fd37d85f2a
Author: Michael Bianco <iloveitaly@gmail.com>
Date:   Thu Mar 7 20:32:53 2019 -0700

    Version bump

diff --git a/lib/netsuite/version.rb b/lib/netsuite/version.rb
index cccfe44..23293d4 100644
--- a/lib/netsuite/version.rb
+++ b/lib/netsuite/version.rb
@@ -1,3 +1,3 @@
 module NetSuite
-  VERSION = '0.8.3'
+  VERSION = '0.8.4'
 end
```

For 0.8.5 its: 659d4634e8ab2ae26d8a860ecb5fc47a803da7c7
```
commit 659d4634e8ab2ae26d8a860ecb5fc47a803da7c7
Author: Michael Bianco <iloveitaly@gmail.com>
Date:   Wed Jul 10 21:02:22 2019 -0600

    Version bump

diff --git a/lib/netsuite/version.rb b/lib/netsuite/version.rb
index 115ab03..763b660 100644
--- a/lib/netsuite/version.rb
+++ b/lib/netsuite/version.rb
@@ -1,3 +1,3 @@
 module NetSuite
-  VERSION = '0.8.4.1'
+  VERSION = '0.8.5'
 end
```

**Comment by iloveitaly** [comment]
@mawaldne thanks! Just added these to the repo.
