### ISSUE TITLE
Inconsistency with Segments

### ISSUE THREAD

**Issue by toyhammered** [NetSweet/netsuite#447]
Both [Department](https://github.com/NetSweet/netsuite/blob/05b8a16a60a26a35e4124bf9b315b9fef046c2fa/lib/netsuite/records/department.rb#L14) and [Location](https://github.com/NetSweet/netsuite/blob/05b8a16a60a26a35e4124bf9b315b9fef046c2fa/lib/netsuite/records/location.rb#L19) have a `record_refs: :parent` while [Classifcation](https://github.com/NetSweet/netsuite/blob/05b8a16a60a26a35e4124bf9b315b9fef046c2fa/lib/netsuite/records/classification.rb#L12) has a `fields: :parent`. 
Would it be possible to add it as a record_refs so it can be consistent with other segments?

**Comment by iloveitaly** [comment]
@toyhammered yes! Want to submit a PR with this change?
