### ISSUE TITLE
Absence of Changelog

### ISSUE THREAD

**Issue by nothingisfunny** [NetSweet/netsuite#449]
Currently it is hard to identify which changes happened (and if they were breaking changes) with version updates. Could a changelog be introduced to help with that?

**Comment by iloveitaly** [comment]
@nothingisfunny great suggestion! I've tried to include a lightweight changelog in the notes for each release, but I haven't been diligent about it. I'll try to do this going forward.

Feel free to submit a changelog adding comments retroactively by looking at the diffs between release SHAs.
