### ISSUE TITLE
Recent commit to Classification breaks test suite

### ISSUE THREAD

**Issue by toyhammered** [NetSweet/netsuite#452]
In 1292ddce014df1ec2311d87fce49461c4db4b43f this test: https://github.com/NetSweet/netsuite/blob/master/spec/netsuite/records/classification_spec.rb#L8 is now broken (`custom_field_list`). We should remove it and add the correct test. Assuming it is similar to this: https://github.com/NetSweet/netsuite/blob/master/spec/netsuite/records/note_spec.rb#L22

I think I should have time this weekend to look into and fix.

**Comment by iloveitaly** [comment]
Good catch. Fixed with 4d6ac2f5b4e2dd5b30b2c02bf71192a9374bff5b
