### ISSUE TITLE
Configure NetSuite on a case-by-case basis

### ISSUE THREAD

**Issue by john-diaz** [NetSweet/netsuite#499]
As far as I know, the only way you can configure the NetSuite gem to communicate with the REST API is as follows:
```ruby
NetSuite.configure do
  reset!

  account  netsuite_account_id

  consumer_key     netsuite_consumer_key
  consumer_secret  netsuite_consumer_secret
  token_id netsuite_token_id
  token_secret netsuite_token_secret
  
  api_version      '2016_2'

  endpoint some_endpoint
end

# subsequently performing the following operation should work:
NetSuite::Records::Customer.get(4)
```

However, my usecase makes it possible that the program can have multiple authentication credentials, which run in parallel. For instance, there could be 2 netsuite accounts, each with completely different consumer-credentials/token-credentials/account-id/wsd-endpoint, and they would each run in parallel.

The problem is as follows: How could I make the RubyGem `NetSuite` object configure to two (or three, or `n`) different accounts, and run in parallel with those separate credentials? Here is an example what it would look like for this to work:

```ruby
account_1 = {
  :id => "1234",
  :consumer_key => "1234",
  :consumer_secret => "1234",
  :token_id => "1234",
  :token_secret => "1234",
  :wsd_endpoint => "some.endpoint.com"
}
account_2 = {
  :id => "5678",
  :consumer_key => "5678",
  :consumer_secret => "5678",
  :token_id => "5678",
  :token_secret => "5678",
  :wsd_endpoint => "other.endpoint.com"
}

# Following blocks will run in parallel!
Thread.new do
  netsuite_1 = Netsuite.new(account_1)
  netsuite_1::Records::Customer.get(4)
end
Thread.new do
  netsuite_2 = Netsuite.new(account_2)
  netsuite_2::Records::Customer.get(4)
end
```

So far it seems like this is an impossible task given the current structure of the code. Any thoughts?

**Comment by john-diaz** [comment]
Hello? Is this repo actively maintained?

**Comment by iloveitaly** [comment]
@john-diaz Yes (take a look at the commit log)! Unfortunately, I don't have time for detailed support like this though. I'd recommend joining the slack group and asking your question there.

Here's a PR that was started to fix this issue:

https://github.com/NetSweet/netsuite/pull/320/files

**Comment by john-diaz** [comment]
@iloveitaly Thank you for taking the time! I completely understand. I'll go ahead and close this issue, since I think there are ways to address this that don't require changes to the code-base.

If anyone runs into this issue in the future (where you want to run two processes in parallel which won't cause the Netsuite gem to overwrite each other's config), I would suggest either (1) Run the threads serially instead of in parallel (In my case I will just use a Mutex lock for the jobs and requeue) or (2) Start a brand new sub-process with it's own stack/heap so that they can't access/overwrite each others memory

Cheers!
