### ISSUE TITLE
NetSuite::Records::Solution description field is truncated

### ISSUE THREAD

**Issue by newplasticideas** [NetSweet/netsuite#519]
```
NetSuite::Records::Solution.search({
  criteria: { saved: 1685 },
  preferences: { page_size: 1000, body_fields_only: false }
}).results
```

the description fields in the returned array of solutions have `(more...)` baked into the end of the full value if it passes a certain length. Please disregard if I'm simply passing the wrong options, but it's been a few days and am unsure of a workaround.

**Comment by iloveitaly** [comment]
@newplasticideas My guess is that's an issue with how your NetSuite account is configured and not something that the gem can help with. Join the slack group and post there, maybe some folks have ideas!

**Comment by newplasticideas** [comment]
@iloveitaly no problem! I'll keep digging. Thanks
