### ISSUE TITLE
Add :klass field to record VendorReturnAuthorization

### ISSUE THREAD

**Issue by shubhrathasetty** [NetSweet/netsuite#575]
please add :klass fields to record VendorReturnAuthorizationItem and VendorReturnAuthorization

NoMethodError: undefined method `klass=' for #<NetSuite::Records::VendorReturnAuthorizationItem:0x00007fb216d14de8 @attributes={:item=>#<NetSuite::Records::RecordRef:0x00007fb216d1be90 @internal_id="555", @external_id=nil, @type=nil, @attributes={:name=>"0901JKE"}>, :line=>"2", :quantity=>"15.0", :description=>"", :rate=>"0.00", :amount=>"0.0", :location=>#<NetSuite::Records::RecordRef:0x00007fb216d1ba58 @internal_id="63", @external_id=nil, @type=nil, @attributes={:name=>""}>, :is_billable=>false, :is_closed=>false, :is_drop_shipment=>false}>

**Comment by iloveitaly** [comment]
This has been done
